/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author naila
 */
public class VistaEntidad extends javax.swing.JFrame {

    /**
     * Creates new form VistaEntidad
     */
    public VistaEntidad() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fabricante = new javax.swing.JPanel();
        combo_fabricante = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        text_id_fabricante = new javax.swing.JTextField();
        boton_envia_fabricante = new javax.swing.JButton();
        text_fabricante = new javax.swing.JTextField();
        panel_linea_producto = new javax.swing.JPanel();
        combo_linea_producto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        text_id_linea_producto = new javax.swing.JTextField();
        boton_envia_liena_producto = new javax.swing.JButton();
        text_linea_producto = new javax.swing.JTextField();
        panel_modelo = new javax.swing.JPanel();
        combo_modelo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        text_id_modelo = new javax.swing.JTextField();
        boton_envia_modelo = new javax.swing.JButton();
        text_modelo = new javax.swing.JTextField();
        panel_version = new javax.swing.JPanel();
        combo_version = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        text_id_version = new javax.swing.JTextField();
        boton_envia_version = new javax.swing.JButton();
        text_version = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_fabricante.setBorder(javax.swing.BorderFactory.createTitledBorder("Fabricante"));

        jLabel1.setText("ID:");

        text_id_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_id_fabricanteActionPerformed(evt);
            }
        });

        boton_envia_fabricante.setText(">>");
        boton_envia_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_envia_fabricanteActionPerformed(evt);
            }
        });

        text_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_fabricanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fabricanteLayout = new javax.swing.GroupLayout(panel_fabricante);
        panel_fabricante.setLayout(panel_fabricanteLayout);
        panel_fabricanteLayout.setHorizontalGroup(
            panel_fabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fabricanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_id_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_fabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_envia_fabricante)
                .addGap(58, 58, 58))
        );
        panel_fabricanteLayout.setVerticalGroup(
            panel_fabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fabricanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(text_id_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_envia_fabricante)
                    .addComponent(text_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_linea_producto.setBorder(javax.swing.BorderFactory.createTitledBorder("Linea de Prducto"));

        jLabel2.setText("ID:");

        text_id_linea_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_id_linea_productoActionPerformed(evt);
            }
        });

        boton_envia_liena_producto.setText(">>");

        javax.swing.GroupLayout panel_linea_productoLayout = new javax.swing.GroupLayout(panel_linea_producto);
        panel_linea_producto.setLayout(panel_linea_productoLayout);
        panel_linea_productoLayout.setHorizontalGroup(
            panel_linea_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_linea_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_linea_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_id_linea_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_linea_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_envia_liena_producto)
                .addGap(53, 53, 53))
        );
        panel_linea_productoLayout.setVerticalGroup(
            panel_linea_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_linea_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_linea_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_linea_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(text_id_linea_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_envia_liena_producto)
                    .addComponent(text_linea_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_modelo.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        jLabel3.setText("ID:");

        text_id_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_id_modeloActionPerformed(evt);
            }
        });

        boton_envia_modelo.setText(">>");

        text_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_modeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_modeloLayout = new javax.swing.GroupLayout(panel_modelo);
        panel_modelo.setLayout(panel_modeloLayout);
        panel_modeloLayout.setHorizontalGroup(
            panel_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modeloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_id_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_modelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_envia_modelo)
                .addGap(46, 46, 46))
        );
        panel_modeloLayout.setVerticalGroup(
            panel_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modeloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(text_id_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_envia_modelo)
                    .addComponent(text_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_version.setBorder(javax.swing.BorderFactory.createTitledBorder("Version"));

        jLabel4.setText("ID:");

        text_id_version.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_id_versionActionPerformed(evt);
            }
        });

        boton_envia_version.setText(">>");

        javax.swing.GroupLayout panel_versionLayout = new javax.swing.GroupLayout(panel_version);
        panel_version.setLayout(panel_versionLayout);
        panel_versionLayout.setHorizontalGroup(
            panel_versionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_versionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_version, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_id_version, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_version)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_envia_version)
                .addGap(40, 40, 40))
        );
        panel_versionLayout.setVerticalGroup(
            panel_versionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_versionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_versionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(text_id_version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_envia_version)
                    .addComponent(text_version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_fabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_linea_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_version, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_linea_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_id_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_id_fabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_id_fabricanteActionPerformed

    private void text_id_linea_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_id_linea_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_id_linea_productoActionPerformed

    private void text_id_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_id_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_id_modeloActionPerformed

    private void text_id_versionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_id_versionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_id_versionActionPerformed

    private void boton_envia_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_envia_fabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_envia_fabricanteActionPerformed

    private void text_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_fabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_fabricanteActionPerformed

    private void text_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_modeloActionPerformed
        
    }//GEN-LAST:event_text_modeloActionPerformed


    public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEntidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_envia_fabricante;
    public javax.swing.JButton boton_envia_liena_producto;
    public javax.swing.JButton boton_envia_modelo;
    public javax.swing.JButton boton_envia_version;
    public javax.swing.JComboBox<String> combo_fabricante;
    public javax.swing.JComboBox<String> combo_linea_producto;
    public javax.swing.JComboBox<String> combo_modelo;
    public javax.swing.JComboBox<String> combo_version;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel panel_fabricante;
    public javax.swing.JPanel panel_linea_producto;
    public javax.swing.JPanel panel_modelo;
    public javax.swing.JPanel panel_version;
    public javax.swing.JTextField text_fabricante;
    public javax.swing.JTextField text_id_fabricante;
    public javax.swing.JTextField text_id_linea_producto;
    public javax.swing.JTextField text_id_modelo;
    public javax.swing.JTextField text_id_version;
    public javax.swing.JTextField text_linea_producto;
    public javax.swing.JTextField text_modelo;
    public javax.swing.JTextField text_version;
    // End of variables declaration//GEN-END:variables
}
