/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_usuarios;

/**
 *
 * @author naila
 */
public class JpanelPublicidadUno extends javax.swing.JPanel {

    /**
     * Creates new form JpanelPublicidadUno
     */
    public JpanelPublicidadUno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_pais = new javax.swing.JComboBox<>();
        boton_imagen_uno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text_telefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_url = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_titulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panel_publicitario_mini = new javax.swing.JPanel();
        labe_imagen_publicidad_mini = new javax.swing.JLabel();
        Label_inferior_publicidad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        combo_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Belice", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica", "Ecuador", "El Salvador", "Guatemala", "Guyana", "Honduras", "Nicaragua", "Panamá", "Paraguay", "Perú", "Surinam", "Uruguay", "Venezuela" }));

        boton_imagen_uno.setText("Cargar Imagen Mini");

        jLabel1.setText("Descripcion y Contactos (Telefono)");

        jLabel2.setText("Link Web o (link de Facebook, Instagram,Twitter)");

        jLabel3.setText("Pais");

        jLabel4.setText("Titulo Corto");

        panel_publicitario_mini.setLayout(new java.awt.BorderLayout());

        labe_imagen_publicidad_mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Git_taller_anuncio_System.jpg"))); // NOI18N
        panel_publicitario_mini.add(labe_imagen_publicidad_mini, java.awt.BorderLayout.CENTER);

        Label_inferior_publicidad.setForeground(new java.awt.Color(255, 51, 51));
        Label_inferior_publicidad.setText("Servicio \"Altamente Profesional\"  (313-694.67.37) Bogotá");
        panel_publicitario_mini.add(Label_inferior_publicidad, java.awt.BorderLayout.PAGE_END);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel5.setText("Publicidad de Prueba.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(text_url, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panel_publicitario_mini, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3)
                            .addComponent(boton_imagen_uno))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(boton_imagen_uno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_publicitario_mini, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Label_inferior_publicidad;
    public javax.swing.JButton boton_imagen_uno;
    public javax.swing.JComboBox<String> combo_pais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel labe_imagen_publicidad_mini;
    public javax.swing.JPanel panel_publicitario_mini;
    public javax.swing.JTextField text_telefono;
    public javax.swing.JTextField text_titulo;
    public javax.swing.JTextField text_url;
    // End of variables declaration//GEN-END:variables
}
