/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas_usuarios;

/**
 *
 * @author naila
 */
public class VistaPublicidad extends javax.swing.JFrame {

    /**
     * Creates new form VistaPublicidad
     */
    public VistaPublicidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_contenedor = new javax.swing.JPanel();
        panel_inferior = new javax.swing.JPanel();
        boton_uno = new javax.swing.JButton();
        boton_dos = new javax.swing.JButton();
        boton_tres = new javax.swing.JButton();
        boton_enviar = new javax.swing.JButton();
        panel_izquierdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_dinamico_publicidad = new javax.swing.JPanel();
        panel_izquierdo_informativo = new javax.swing.JPanel();
        Label_activas = new javax.swing.JLabel();
        Label_espera = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        lablel_superior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_contenedor.setLayout(new java.awt.BorderLayout());

        panel_inferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        boton_uno.setText("Paso(1)");
        panel_inferior.add(boton_uno);

        boton_dos.setText("Paso(2)");
        panel_inferior.add(boton_dos);

        boton_tres.setText("Paso(3)");
        panel_inferior.add(boton_tres);

        boton_enviar.setText("Enviar");
        panel_inferior.add(boton_enviar);

        panel_contenedor.add(panel_inferior, java.awt.BorderLayout.PAGE_END);

        panel_izquierdo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_izquierdo.setLayout(new javax.swing.BoxLayout(panel_izquierdo, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Mi Publicidad");
        panel_izquierdo.add(jLabel1);

        panel_dinamico_publicidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_dinamico_publicidad.setLayout(new javax.swing.BoxLayout(panel_dinamico_publicidad, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panel_dinamico_publicidad);

        panel_izquierdo.add(jScrollPane1);

        panel_izquierdo_informativo.setLayout(new javax.swing.BoxLayout(panel_izquierdo_informativo, javax.swing.BoxLayout.Y_AXIS));

        Label_activas.setText("Activas:");
        panel_izquierdo_informativo.add(Label_activas);

        Label_espera.setText("Espera:");
        panel_izquierdo_informativo.add(Label_espera);

        label_total.setText("Total:");
        panel_izquierdo_informativo.add(label_total);

        panel_izquierdo.add(panel_izquierdo_informativo);

        panel_contenedor.add(panel_izquierdo, java.awt.BorderLayout.LINE_START);

        lablel_superior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lablel_superior.setText("*****");
        panel_contenedor.add(lablel_superior, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panel_contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPublicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPublicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPublicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPublicidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPublicidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Label_activas;
    public javax.swing.JLabel Label_espera;
    public javax.swing.JButton boton_dos;
    public javax.swing.JButton boton_enviar;
    public javax.swing.JButton boton_tres;
    public javax.swing.JButton boton_uno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel label_total;
    public javax.swing.JLabel lablel_superior;
    public javax.swing.JPanel panel_contenedor;
    public javax.swing.JPanel panel_dinamico_publicidad;
    public javax.swing.JPanel panel_inferior;
    public javax.swing.JPanel panel_izquierdo;
    private javax.swing.JPanel panel_izquierdo_informativo;
    // End of variables declaration//GEN-END:variables
}
